import Head from "next/head";
import styles from "@/styles/assignments/Home.module.css";
import Link from "next/link";
import Assignment from "@/components/assignments/Assignment";
import React, { useState, useEffect } from "react";
 
import { useSession} from 'next-auth/react';

export default function Home() {
  const {data} = useSession()
  const [assignments, setAssignments] = useState(null);

  const getAssignments = async () => {
    const res = await fetch("http://localhost:8000/assignments/assignment/");
    const data = await res.json();
    setAssignments(data);
  };

  useEffect(() => {
    getAssignments();
  },[data]);

  const deleteAssignment = async (assignmentId) => {
    const response = await fetch(
      `http://localhost:8000/assignments/assignment/${assignmentId}/delete/`,
      {
        method: "DELETE",
        headers: {
          Authorization: `Bearer ${data.user.access_token}`,
        },
      }
    );

    if (response.ok) {
      console.log("Assignment deleted successfully");
    } else {
      console.error("Failed to delete assignment");
    }

    getAssignments();
  };

  if (!assignments) {
    return (
      <div className={styles.loading}>
        <h1>Loading....</h1>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Enabled-Assignments</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        <div className={styles.header}>
          <h1>Assignments</h1>
          <Link
            href="/assignments/add"
            className={styles.addAssignment}
          >
            Add Assignment
          </Link>
        </div>

        {assignments.length > 0 && (
          <div className={styles.assignmentsContainer}>
            {assignments.map((assignment) => (
                <Assignment
                key={assignment.id}
                assignment={assignment}
                deleteAssignment={deleteAssignment}
                getAssignments={getAssignments}
              /> 
            ))}
          </div>
        )}
        {assignments.length === 0 && (
          <div className={styles.noAssignments}>
            <h5>No Assignments!</h5>
          </div>
        )}
      </main>
    </>
  );
}